# Generated by Django 4.2.7 on 2024-03-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliQuest_v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.AddField(
            model_name='author',
            name='authorID',
            field=models.CharField(default='default_test', max_length=50, primary_key=True, serialize=False),
        ),
    ]
