# Generated by Django 4.2.7 on 2024-03-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliQuest_v1', '0002_remove_author_id_author_authorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
