# Generated by Django 4.2.7 on 2024-04-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliQuest_v1', '0002_paper_papersource_paperdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperdetail',
            name='downloadlink',
            field=models.URLField(null=True),
        ),
    ]
