# Generated by Django 4.2.7 on 2024-03-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliQuest_v1', '0003_alter_author_email_alter_paper_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
