# Generated by Django 5.0.3 on 2024-03-27 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfileApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalinfo",
            old_name="username",
            new_name="user",
        ),
    ]
